name: ExecuteEverywhere
authors: [vemacs, A248]
main: space.arim.executeeverywhere.bukkit.ExecuteEverywhereBukkit
version: ${project.version}
api-version: 1.16

commands:
  eebukkit:
    usage: /eebukkit <command>
    description: Send a command from the backend to the proxy
